"""Command-line entry point."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from boardkit import __version__
from boardkit.board import (
    DEFERRED_VIEW,
    BoardError,
    build_board,
    phantom_deferrals,
    render_canary_key,
    view_drift,
)
from boardkit.brief import BriefError, build_brief
from boardkit.config import (
    BOARD_ENV_VAR,
    BOARDKIT_DIRNAME,
    CONFIG_FILENAME,
    MANIFEST_FILENAME,
    Config,
    board_row_errors,
    charter_route_errors,
    find_boardkit,
    git_common_boardkit,
    load_config,
    registry_rows,
    resolve_board,
)
from boardkit.contract import (
    BOARD_DOCS,
    CONTRACT_VERSION,
    DATA_DIR,
    ENTRY_SHIMS,
    REQUIRED_ROLES,
    TEMPLATES_DIR,
    ContractError,
    render_resolution_json,
    render_resolution_text,
    resolve_role,
)
from boardkit.doctor import render_json, render_text, run_doctor
from boardkit.review_packet import ReviewPacketError, build_review_packet

TEMPLATE_SOURCE = DATA_DIR / "_template.md"

INIT_CONFIG_TEMPLATE = """\
# boardkit.toml — generated by `boardkit init`

[board]
# Directory (relative to this file) holding the card registry.
cards_dir = "docs/board/cards"
# Prefix for numbered card ids, e.g. "S" for S1, S2, ...
id_prefix = "S"
# Non-numbered card ids that stand outside the prefix scheme.
sentinel_ids = ["MILESTONE"]

[review]
# Path (relative to this file) to the git repo review packets diff against.
repo = "."
# Directory (relative to this file) review packets are written to.
output_dir = "docs/board/reviews"

# The delegation contract: which transport serves each role. Scaffolded with
# placeholders — fill them in, then run `boardkit doctor`.
[contract]
version = 2

# One [routes.<name>] table per transport you can dispatch to. Names are
# lowercase slugs.
[routes.primary]
# The harness this transport reaches.
adapter = "<harness-name>"
# Child skill this transport loads; "" means none.
skill = ""
# Where live model pins are read at dispatch time. A pointer, never a pin:
# model ids go stale, so the contract records where to look them up.
pin_source = "docs/board/REVIEW-TOOLING.md#harness-bindings"
# Commands that prove the transport is reachable. boardkit prints preflight;
# it never runs it — the caller runs them.
preflight = []
# The transport's read contract, printed with every resolution:
# "working-dir" (stage the packet into the working directory; outside
# reads are refused) or "repo-native" (cwd at the repo under review,
# repo-native paths; staged copies outside a git repo stall silently).
staging = "<working-dir or repo-native>"

# One [roles.<name>] table per required role. `routes` is the ordered
# fallback list; every name must be declared above.
[roles.executor]
routes = ["primary"]

[roles.code-review]
routes = ["primary"]

[roles.prose-review]
routes = ["primary"]

[roles.frontier-review]
routes = ["primary"]

[roles.drift-audit]
routes = ["primary"]

[roles.canary]
routes = ["primary"]
"""


def _fail(errors: list[str]) -> int:
    for e in errors:
        print(f"ERROR: {e}", file=sys.stderr)
    return 1


def _resolve_config(args: argparse.Namespace) -> Config:
    """Load the board this invocation targets.

    `--config` names a boardkit.toml directly and wins outright; otherwise
    the R5' resolution order runs: `--board`, then BOARDKIT_BOARD, then the
    `.boardkit/` walk-up with its git common-dir fallback, then the legacy
    walk-up.
    """
    if args.config is not None:
        return load_config(Path(args.config).resolve())
    resolution = resolve_board(Path.cwd(), board=args.board)
    return load_config(resolution.config_path)


def cmd_check(args: argparse.Namespace) -> int:
    config = _resolve_config(args)
    try:
        result = build_board(config)
    except BoardError as exc:
        return _fail(exc.errors)

    errors = view_drift(config, result.views)
    # A board reachable through a manifest must agree with its registry row,
    # and a charter's route targets must resolve to registry short-codes.
    errors += board_row_errors(config, Path.cwd())
    errors += charter_route_errors(config, Path.cwd())
    if errors:
        return _fail(errors)
    if config.charter is None:
        print("WARN no [charter] block in boardkit.toml (R10: every board grows one)")
    for warning in phantom_deferrals(result.cards):
        print(f"WARN {warning}")
    print(f"OK: {len(result.cards)} cards valid, views current")
    return 0


def cmd_render(args: argparse.Namespace) -> int:
    config = _resolve_config(args)
    try:
        result = build_board(config)
    except BoardError as exc:
        return _fail(exc.errors)

    for name, content in result.views.items():
        (config.board.cards_dir / name).write_text(content, encoding="utf-8")
    stale_deferred = config.board.cards_dir / DEFERRED_VIEW
    if DEFERRED_VIEW not in result.views and stale_deferred.exists():
        stale_deferred.unlink()  # the last deferral was resolved
    written = ", ".join(sorted(result.views))
    print(f"OK: {len(result.cards)} cards valid; wrote {written}")
    return 0


def cmd_canary_key(args: argparse.Namespace) -> int:
    config = _resolve_config(args)
    try:
        result = build_board(config)
    except BoardError as exc:
        return _fail(exc.errors)

    drift = [e.split(":", 1)[0] for e in view_drift(config, result.views)]
    print(render_canary_key(result, drift), end="")
    return 0


def cmd_boards(args: argparse.Namespace) -> int:
    """Enumerate the family from the registry (R4: the manifest IS it)."""
    boardkit_dir = find_boardkit(Path.cwd()) or git_common_boardkit(Path.cwd())
    if boardkit_dir is None:
        return _fail(
            [
                f"no {BOARDKIT_DIRNAME}/{MANIFEST_FILENAME} found from {Path.cwd()}; "
                "the boards registry is the manifest"
            ]
        )
    rows, errors = registry_rows(boardkit_dir)

    if args.json:
        payload = {
            "manifest": str(boardkit_dir / MANIFEST_FILENAME),
            "boards": [
                {
                    "code": row.code,
                    "default": row.default,
                    "location": (
                        row.entry.location.scheme
                        if not row.entry.location.value
                        else f"{row.entry.location.scheme}:{row.entry.location.value}"
                    ),
                    "engine": row.entry.engine,
                    "id_prefix": row.effective_prefix,
                    "scope": row.entry.scope,
                    "status": row.entry.status,
                    "resolved_root": (
                        str(row.resolved_root) if row.resolved_root is not None else None
                    ),
                    "reachable": bool(
                        row.resolved_root is not None
                        and (row.resolved_root / CONFIG_FILENAME).is_file()
                    ),
                }
                for row in rows
            ],
            "errors": errors,
        }
        print(json.dumps(payload, indent=2))
        return 1 if errors else 0

    print(f"boards registry: {boardkit_dir / MANIFEST_FILENAME}")
    header = ("code", "engine", "prefix", "status", "home", "scope")
    table: list[tuple[str, ...]] = [header]
    for row in rows:
        loc = row.entry.location
        if row.resolved_root is None:
            home = f"{loc.scheme} (unresolved here; add {BOARDKIT_DIRNAME}/local.toml)"
        elif not (row.resolved_root / CONFIG_FILENAME).is_file():
            home = f"{row.resolved_root} (no {CONFIG_FILENAME})"
        else:
            home = str(row.resolved_root)
        table.append(
            (
                row.code + (" *" if row.default else ""),
                row.entry.engine or "-",
                row.effective_prefix or "-",
                row.entry.status,
                home,
                row.entry.scope or "-",
            )
        )
    widths = [max(len(line[col]) for line in table) for col in range(len(header))]
    for line in table:
        print(
            "  ".join(cell.ljust(width) for cell, width in zip(line, widths, strict=True)).rstrip()
        )
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    return 1 if errors else 0


def cmd_doctor(args: argparse.Namespace) -> int:
    # Doctor never raises, so board resolution failures downgrade to the
    # config-absent finding path rather than a traceback; a malformed
    # manifest still refuses loudly (ValueError reaches main's handler).
    config_arg = args.config
    if config_arg is None:
        try:
            config_arg = str(resolve_board(Path.cwd(), board=args.board).config_path)
        except FileNotFoundError:
            config_arg = None
    report = run_doctor(config_arg, Path.cwd())
    print(render_json(report) if args.json else render_text(report), end="")
    return 1 if report.errors else 0


def cmd_resolve_route(args: argparse.Namespace) -> int:
    config = _resolve_config(args)
    try:
        resolution = resolve_role(config, args.role)
    except ContractError as exc:
        return _fail([str(exc)])

    print(
        render_resolution_json(resolution) if args.json else render_resolution_text(resolution),
        end="",
    )
    return 0


def cmd_dispatch_brief(args: argparse.Namespace) -> int:
    config = _resolve_config(args)
    try:
        brief = build_brief(config, args.card_id)
    except (BoardError, BriefError) as exc:
        return _fail(exc.errors if isinstance(exc, BoardError) else [str(exc)])

    print(brief, end="")
    return 0


def cmd_review_packet(args: argparse.Namespace) -> int:
    config = _resolve_config(args)
    repo = Path(args.repo).resolve() if args.repo is not None else None
    try:
        outdir = build_review_packet(
            config,
            args.card_id,
            repo=repo,
            suffix=args.suffix,
            commit_range=args.commit_range,
        )
    except ReviewPacketError as exc:
        return _fail([str(exc)])

    print(f"OK: review packet -> {outdir}")
    print(f"Start at {outdir / 'REVIEW.md'}")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    root = Path(args.config).resolve().parent if args.config is not None else Path.cwd()
    config_path = root / CONFIG_FILENAME
    if config_path.exists():
        return _fail([f"{config_path} already exists; refusing to overwrite"])

    cards_dir = root / "docs" / "board" / "cards"
    template_dest = cards_dir / "_template.md"
    if template_dest.exists():
        return _fail([f"{template_dest} already exists; refusing to overwrite"])

    for _source_name, rel_dest in BOARD_DOCS:
        if (root / rel_dest).exists():
            return _fail([f"{root / rel_dest} already exists; refusing to overwrite"])

    cards_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(TEMPLATE_SOURCE, template_dest)
    config_path.write_text(INIT_CONFIG_TEMPLATE, encoding="utf-8")

    for source_name, rel_dest in BOARD_DOCS:
        dest = root / rel_dest
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(TEMPLATES_DIR / source_name, dest)

    skipped: list[Path] = []
    for source_name, rel_dest in ENTRY_SHIMS:
        dest = root / rel_dest
        if dest.exists():
            skipped.append(dest)
            continue
        shutil.copyfile(TEMPLATES_DIR / source_name, dest)

    config = load_config(config_path)

    # review packets are local working material; install the gitignore contract
    gitignore = root / ".gitignore"
    ignore_line = config.review.output_dir.relative_to(root).as_posix() + "/"
    existing_ignore = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    if ignore_line not in existing_ignore.splitlines():
        with gitignore.open("a", encoding="utf-8") as f:
            if existing_ignore and not existing_ignore.endswith("\n"):
                f.write("\n")
            f.write(f"{ignore_line}\n")

    result = build_board(config)
    for name, content in result.views.items():
        (config.board.cards_dir / name).write_text(content, encoding="utf-8")

    print(f"OK: scaffolded {config_path}, {cards_dir}, and docs/board; `boardkit check` is clean")
    print(f"Stamped at delegation contract v{CONTRACT_VERSION}.")
    for dest in skipped:
        print(
            f"NOTE: {dest} already exists; left untouched. Merge the boardkit entry "
            f"points from {TEMPLATES_DIR} yourself."
        )
    # init scaffolds placeholders rather than lying, so the board is not yet
    # dispatchable; say what is left instead of leaving that to be discovered.
    print(
        "NEXT: fill the [routes.*] tables in boardkit.toml and the fill-in sections "
        "of docs/board/REVIEW-TOOLING.md, then run `boardkit doctor`."
    )
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="boardkit")
    parser.add_argument(
        "--config",
        default=None,
        help=f"path to {CONFIG_FILENAME} (wins over all board resolution)",
    )
    parser.add_argument(
        "--board",
        default=None,
        help=(
            "board short-code (resolved via .boardkit/manifest.toml) or a path "
            f"containing {CONFIG_FILENAME}; beats {BOARD_ENV_VAR} and the walk-up"
        ),
    )
    parser.add_argument("--version", action="version", version=f"boardkit {__version__}")
    subparsers = parser.add_subparsers(dest="command")

    check = subparsers.add_parser("check", help="validate the board and diff generated views")
    check.set_defaults(handler=cmd_check)

    render = subparsers.add_parser(
        "render", help="validate the board and write its generated views"
    )
    render.set_defaults(handler=cmd_render)

    boards = subparsers.add_parser(
        "boards", help="enumerate the board family from the .boardkit manifest registry"
    )
    boards.set_defaults(handler=cmd_boards)
    boards.add_argument(
        "--json", action="store_true", help="emit the registry as JSON with stable fields"
    )

    doctor = subparsers.add_parser(
        "doctor", help="diagnose whether this repo's board installation is ready to run"
    )
    doctor.set_defaults(handler=cmd_doctor)
    doctor.add_argument(
        "--json", action="store_true", help="emit the report as JSON with stable check ids"
    )

    resolve = subparsers.add_parser(
        "resolve-route", help="print the transport that serves one delegation role"
    )
    resolve.set_defaults(handler=cmd_resolve_route)
    resolve.add_argument("role", help=f"one of: {', '.join(REQUIRED_ROLES)}")
    resolve.add_argument("--json", action="store_true", help="emit the resolution as JSON")

    brief = subparsers.add_parser(
        "dispatch-brief", help="generate one card's dispatch brief (markdown, on stdout)"
    )
    brief.set_defaults(handler=cmd_dispatch_brief)
    brief.add_argument("card_id", help="card id, for example S2")

    review = subparsers.add_parser("review-packet", help="build a per-card review packet")
    review.set_defaults(handler=cmd_review_packet)
    review.add_argument("card_id", help="card id, for example S2")
    review.add_argument("--repo", default=None, help="worktree holding the card's commits")
    review.add_argument(
        "--suffix",
        default=None,
        help=(
            "name the repo this packet covers, for a card spanning more than one "
            "repo: output goes to <id>-<suffix> (lowercase slug)"
        ),
    )
    review.add_argument(
        "--commit-range",
        default=None,
        help=(
            "range A..B to diff instead of the card's commit-range frontmatter, "
            "for the second repo of a card whose work spans more than one"
        ),
    )

    canary_key = subparsers.add_parser(
        "canary-key",
        help="print the orientation canary's grading key (markdown)",
    )
    canary_key.set_defaults(handler=cmd_canary_key)

    init = subparsers.add_parser("init", help="scaffold a new board in the current directory")
    init.set_defaults(handler=cmd_init)

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.command is None:
        print(f"boardkit {__version__}")
        parser.print_help()
        return

    try:
        sys.exit(args.handler(args))
    except ValueError as exc:
        # Config and contract load errors (including the v1 migration
        # refusal) are user-facing refusals, not crashes: one ERROR line,
        # exit 1, no traceback burying the remedy.
        sys.exit(_fail([str(exc)]))
