"""Command-line entry point."""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

from boardkit import __version__
from boardkit.board import BoardError, build_board
from boardkit.config import CONFIG_FILENAME, Config, load_config
from boardkit.review_packet import ReviewPacketError, build_review_packet

DATA_DIR = Path(__file__).resolve().parent / "data"
TEMPLATE_SOURCE = DATA_DIR / "_template.md"
TEMPLATES_DIR = DATA_DIR / "templates"

# (template filename, destination relative to the repo root)
BOARD_DOCS = [
    ("PROCESS.md", Path("docs/board/PROCESS.md")),
    ("MODEL-CLASSES.md", Path("docs/board/MODEL-CLASSES.md")),
    ("REVIEW-TOOLING.md.template", Path("docs/board/REVIEW-TOOLING.md")),
]
ENTRY_SHIMS = [
    ("AGENTS.md.template", Path("AGENTS.md")),
    ("CLAUDE.md.template", Path("CLAUDE.md")),
    ("GEMINI.md.template", Path("GEMINI.md")),
]

INIT_CONFIG_TEMPLATE = """\
# boardkit.toml — generated by `boardkit init`

[board]
# Directory (relative to this file) holding the card registry.
cards_dir = "docs/board/cards"
# Prefix for numbered card ids, e.g. "S" for S1, S2, ...
id_prefix = "S"
# Non-numbered card ids that stand outside the prefix scheme.
sentinel_ids = ["MILESTONE"]

[review]
# Path (relative to this file) to the git repo review packets diff against.
repo = "."
# Directory (relative to this file) review packets are written to.
output_dir = "docs/board/reviews"
"""


def _fail(errors: list[str]) -> int:
    for e in errors:
        print(f"ERROR: {e}", file=sys.stderr)
    return 1


def _resolve_config(config_arg: str | None) -> Config:
    path = Path(config_arg).resolve() if config_arg is not None else None
    return load_config(path)


def cmd_check(args: argparse.Namespace) -> int:
    config = _resolve_config(args.config)
    try:
        result = build_board(config)
    except BoardError as exc:
        return _fail(exc.errors)

    errors: list[str] = []
    for name, want in result.views.items():
        path = config.board.cards_dir / name
        if not path.exists():
            errors.append(f"{name}: missing; run `boardkit render` to generate")
        elif path.read_text(encoding="utf-8") != want:
            errors.append(f"{name}: drift from frontmatter; regenerate (drags count)")
    if errors:
        return _fail(errors)
    print(f"OK: {len(result.cards)} cards valid, views current")
    return 0


def cmd_render(args: argparse.Namespace) -> int:
    config = _resolve_config(args.config)
    try:
        result = build_board(config)
    except BoardError as exc:
        return _fail(exc.errors)

    for name, content in result.views.items():
        (config.board.cards_dir / name).write_text(content, encoding="utf-8")
    print(f"OK: {len(result.cards)} cards valid; wrote INDEX.md and board.md")
    return 0


def cmd_review_packet(args: argparse.Namespace) -> int:
    config = _resolve_config(args.config)
    repo = Path(args.repo).resolve() if args.repo is not None else None
    try:
        outdir = build_review_packet(config, args.card_id, repo=repo)
    except ReviewPacketError as exc:
        return _fail([str(exc)])

    print(f"OK: review packet -> {outdir}")
    print(f"Start at {outdir / 'REVIEW.md'}")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    root = Path(args.config).resolve().parent if args.config is not None else Path.cwd()
    config_path = root / CONFIG_FILENAME
    if config_path.exists():
        return _fail([f"{config_path} already exists; refusing to overwrite"])

    cards_dir = root / "docs" / "board" / "cards"
    template_dest = cards_dir / "_template.md"
    if template_dest.exists():
        return _fail([f"{template_dest} already exists; refusing to overwrite"])

    for _source_name, rel_dest in BOARD_DOCS:
        if (root / rel_dest).exists():
            return _fail([f"{root / rel_dest} already exists; refusing to overwrite"])

    cards_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(TEMPLATE_SOURCE, template_dest)
    config_path.write_text(INIT_CONFIG_TEMPLATE, encoding="utf-8")

    for source_name, rel_dest in BOARD_DOCS:
        dest = root / rel_dest
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(TEMPLATES_DIR / source_name, dest)

    skipped: list[Path] = []
    for source_name, rel_dest in ENTRY_SHIMS:
        dest = root / rel_dest
        if dest.exists():
            skipped.append(dest)
            continue
        shutil.copyfile(TEMPLATES_DIR / source_name, dest)

    config = load_config(config_path)
    result = build_board(config)
    for name, content in result.views.items():
        (config.board.cards_dir / name).write_text(content, encoding="utf-8")

    print(f"OK: scaffolded {config_path}, {cards_dir}, and docs/board; `boardkit check` is clean")
    for dest in skipped:
        print(
            f"NOTE: {dest} already exists; left untouched. Merge the boardkit entry "
            f"points from {TEMPLATES_DIR} yourself."
        )
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="boardkit")
    parser.add_argument(
        "--config",
        default=None,
        help=f"path to {CONFIG_FILENAME} (default: walk up from cwd)",
    )
    subparsers = parser.add_subparsers(dest="command")

    subparsers.add_parser("check", help="validate the board and diff generated views")
    subparsers.add_parser("render", help="validate the board and write INDEX.md and board.md")

    review = subparsers.add_parser("review-packet", help="build a per-card review packet")
    review.add_argument("card_id", help="card id, for example S2")
    review.add_argument("--repo", default=None, help="worktree holding the card's commits")

    subparsers.add_parser("init", help="scaffold a new board in the current directory")

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.command is None:
        print(f"boardkit {__version__}")
        parser.print_help()
        return

    commands = {
        "check": cmd_check,
        "render": cmd_render,
        "review-packet": cmd_review_packet,
        "init": cmd_init,
    }
    sys.exit(commands[args.command](args))
